const sources = {
  searchEssentials: "https://developers.google.com/search/docs/essentials",
  technicalRequirements: "https://developers.google.com/search/docs/essentials/technical",
  howSearchWorks: "https://developers.google.com/search/docs/fundamentals/how-search-works",
  crawlableLinks: "https://developers.google.com/search/docs/crawling-indexing/links-crawlable",
  robotsMeta: "https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag",
  robotsTxt: "https://developers.google.com/search/docs/crawling-indexing/robots/intro",
  canonicalization: "https://developers.google.com/search/docs/crawling-indexing/canonicalization",
  consolidateDuplicates: "https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls",
  sitemaps: "https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview",
  javascriptSeo: "https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics",
  helpfulContent: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content",
  aiOptimization: "https://developers.google.com/search/docs/fundamentals/ai-optimization-guide",
  structuredDataIntro: "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data",
  structuredDataPolicies: "https://developers.google.com/search/docs/appearance/structured-data/sd-policies",
  organizationSchema: "https://developers.google.com/search/docs/appearance/structured-data/organization",
  pageExperience: "https://developers.google.com/search/docs/appearance/page-experience",
  coreWebVitals: "https://developers.google.com/search/docs/appearance/core-web-vitals",
  titleLinks: "https://developers.google.com/search/docs/appearance/title-link",
  snippets: "https://developers.google.com/search/docs/appearance/snippet",
  googleImages: "https://developers.google.com/search/docs/appearance/google-images",
  favicon: "https://developers.google.com/search/docs/appearance/favicon-in-search",
  spamPolicies: "https://developers.google.com/search/docs/essentials/spam-policies",
};

const rule = (id, dimension, defaultSeverity, title, recommendation, ruleSources) => ({
  id,
  dimension,
  defaultSeverity,
  title,
  recommendation,
  sources: ruleSources,
});

export const rules = [
  rule(
    "technical.http_error",
    "technical",
    "P0",
    "Important page returns an unsuccessful HTTP status",
    "Fix server, routing, or deployment errors so important pages return a successful status.",
    [sources.technicalRequirements, sources.howSearchWorks],
  ),
  rule(
    "technical.redirect_chain",
    "technical",
    "P2",
    "Page uses a long or unstable redirect chain",
    "Reduce redirects so canonical URLs resolve directly and predictably.",
    [sources.technicalRequirements],
  ),
  rule(
    "technical.https_missing",
    "technical",
    "P1",
    "Page is not available over HTTPS",
    "Serve important pages over HTTPS and redirect HTTP variants to the HTTPS canonical URL.",
    [sources.searchEssentials],
  ),
  rule(
    "technical.rendered_content_missing",
    "technical",
    "P1",
    "Rendered page is missing primary content",
    "Ensure primary content is available in rendered HTML and does not depend on fragile client behavior.",
    [sources.javascriptSeo, sources.technicalRequirements],
  ),
  rule(
    "technical.raw_rendered_mismatch",
    "technical",
    "P2",
    "Raw and rendered page content differ materially",
    "Review JavaScript rendering and hydration so crawlers and users receive consistent primary content.",
    [sources.javascriptSeo],
  ),
  rule(
    "crawl.robots_blocked",
    "crawl_index",
    "P1",
    "robots.txt blocks an important page or resource",
    "Update robots.txt rules so important pages and resources needed for rendering can be crawled.",
    [sources.robotsTxt, sources.technicalRequirements],
  ),
  rule(
    "crawl.sitemap_missing",
    "crawl_index",
    "P2",
    "No sitemap was discovered",
    "Publish a sitemap that lists canonical, indexable URLs for important pages.",
    [sources.sitemaps],
  ),
  rule(
    "crawl.broken_internal_link",
    "crawl_index",
    "P2",
    "Internal link points to an unavailable URL",
    "Fix or remove broken internal links so crawlers and users can move through the site reliably.",
    [sources.crawlableLinks, sources.technicalRequirements],
  ),
  rule(
    "indexability.noindex",
    "crawl_index",
    "P1",
    "Important page has a noindex directive",
    "Remove noindex from pages intended to appear in Google Search.",
    [sources.robotsMeta],
  ),
  rule(
    "indexability.x_robots_noindex",
    "crawl_index",
    "P1",
    "Important page has an X-Robots-Tag noindex directive",
    "Remove X-Robots-Tag noindex from pages intended to appear in Google Search.",
    [sources.robotsMeta],
  ),
  rule(
    "indexability.canonical_missing",
    "crawl_index",
    "P2",
    "Canonical URL is missing",
    "Add a canonical signal to important indexable pages when duplicate or alternate URLs may exist.",
    [sources.canonicalization, sources.consolidateDuplicates],
  ),
  rule(
    "indexability.canonical_target_error",
    "crawl_index",
    "P1",
    "Canonical target is unavailable or not indexable",
    "Point canonical tags to successful, indexable preferred URLs.",
    [sources.canonicalization],
  ),
  rule(
    "indexability.noindex_canonical_conflict",
    "crawl_index",
    "P1",
    "Page combines noindex with a canonical signal",
    "Choose a single indexing strategy: remove noindex for indexable pages or align links and canonical signals to the preferred URL.",
    [sources.robotsMeta, sources.canonicalization],
  ),
  rule(
    "indexability.noncanonical_in_sitemap",
    "crawl_index",
    "P2",
    "Sitemap includes non-canonical URLs",
    "List only canonical, indexable URLs in sitemaps.",
    [sources.sitemaps, sources.canonicalization],
  ),
  rule(
    "appearance.title_missing",
    "search_appearance",
    "P1",
    "Page is missing a title element",
    "Add a unique, descriptive title that reflects the page's main content.",
    [sources.titleLinks],
  ),
  rule(
    "appearance.title_duplicate",
    "search_appearance",
    "P2",
    "Multiple pages use the same title",
    "Write unique titles that distinguish page purpose and topic.",
    [sources.titleLinks],
  ),
  rule(
    "appearance.meta_description_missing",
    "search_appearance",
    "P3",
    "Page is missing a meta description",
    "Add concise, useful page descriptions that can support better snippets.",
    [sources.snippets],
  ),
  rule(
    "appearance.meta_description_duplicate",
    "search_appearance",
    "P3",
    "Multiple pages use the same meta description",
    "Write unique descriptions that summarize each page's specific purpose.",
    [sources.snippets],
  ),
  rule(
    "appearance.h1_missing",
    "search_appearance",
    "P2",
    "Page is missing a clear H1",
    "Add one visible primary heading that describes the page topic.",
    [sources.titleLinks, sources.helpfulContent],
  ),
  rule(
    "appearance.image_alt_missing",
    "search_appearance",
    "P3",
    "Important image is missing alt text",
    "Add descriptive alt text for meaningful images.",
    [sources.googleImages],
  ),
  rule(
    "appearance.favicon_missing",
    "search_appearance",
    "P3",
    "Favicon signal was not discovered",
    "Publish a valid favicon that Google can access.",
    [sources.favicon],
  ),
  rule(
    "structured_data.invalid_jsonld",
    "structured_data",
    "P1",
    "JSON-LD structured data is invalid",
    "Fix JSON-LD syntax so structured data can be parsed reliably.",
    [sources.structuredDataIntro],
  ),
  rule(
    "structured_data.required_property_missing",
    "structured_data",
    "P2",
    "Structured data is missing required properties",
    "Add the required properties for supported schema types when the page's visible content supports the markup.",
    [sources.structuredDataIntro, sources.structuredDataPolicies],
  ),
  rule(
    "structured_data.visible_content_mismatch",
    "structured_data",
    "P1",
    "Structured data does not match visible page content",
    "Keep structured data aligned with user-visible content and Google structured data policies.",
    [sources.structuredDataPolicies],
  ),
  rule(
    "structured_data.organization_missing",
    "structured_data",
    "P2",
    "Organization structured data is missing or unclear",
    "Add Organization structured data where visible business identity supports it.",
    [sources.organizationSchema, sources.structuredDataIntro],
  ),
  rule(
    "performance.lighthouse_poor",
    "performance",
    "P2",
    "Imported Lighthouse performance score is poor",
    "Investigate page weight, render-blocking work, server response time, and client-side execution before treating performance as search-ready.",
    [sources.pageExperience, sources.coreWebVitals],
  ),
  rule(
    "performance.lcp_poor",
    "performance",
    "P2",
    "Largest Contentful Paint is poor",
    "Improve loading of the largest above-the-fold content element by optimizing server response, critical resources, images, and rendering work.",
    [sources.pageExperience, sources.coreWebVitals],
  ),
  rule(
    "performance.cls_poor",
    "performance",
    "P2",
    "Cumulative Layout Shift is poor",
    "Reserve stable layout space for images, embeds, ads, and late-loading UI so visible content does not shift unexpectedly.",
    [sources.pageExperience, sources.coreWebVitals],
  ),
  rule(
    "content.thin_content",
    "helpful_content",
    "P2",
    "Page has limited useful main content",
    "Expand visible content to satisfy the visitor's task with original, helpful information.",
    [sources.helpfulContent],
  ),
  rule(
    "content.answerability_gap",
    "geo_readiness",
    "P2",
    "Page lacks directly answerable sections",
    "Add concise answer sections, definitions, steps, comparisons, FAQs, or evidence where useful.",
    [sources.aiOptimization, sources.helpfulContent],
  ),
  rule(
    "entity.about_contact_missing",
    "entity_clarity",
    "P2",
    "Organization identity or contact details are missing",
    "Make organization identity, contact, and trust details easy to find on crawlable pages.",
    [sources.searchEssentials, sources.organizationSchema],
  ),
  rule(
    "geo.entity_clarity_gap",
    "geo_readiness",
    "P2",
    "Important entities and relationships are unclear",
    "Name products, services, people, locations, and relationships plainly in visible content.",
    [sources.aiOptimization, sources.helpfulContent],
  ),
  rule(
    "policy.hidden_text_risk",
    "policy_risk",
    "P1",
    "Hidden text risk detected",
    "Remove or justify hidden text patterns that could mislead users or search systems.",
    [sources.spamPolicies],
  ),
  rule(
    "policy.duplicate_content_cluster",
    "policy_risk",
    "P2",
    "Large duplicate content cluster detected",
    "Consolidate duplicative pages into stronger canonical resources or clarify unique page value.",
    [sources.consolidateDuplicates, sources.helpfulContent, sources.spamPolicies],
  ),
];

export const getRule = (id) => rules.find((item) => item.id === id);
